# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=10)),
                ('version_api', models.CharField(max_length=10)),
                ('tipo_lenguaje', models.CharField(max_length=20)),
            ],
        ),
    ]
